# Generated by Django 4.1.7 on 2023-05-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='field2',
            field=models.EmailField(max_length=254),
        ),
    ]
